backfill_history:
  fields:
    backfill_days:
      required: false
      selector:
        number:
          min: 0
          max: 3650
          mode: box
    recent_refresh_hours:
      required: false
      selector:
        number:
          min: 0
          max: 168
          mode: box
    history_granularity:
      required: false
      selector:
        select:
          options:
            - monthly
            - quarter_hour
    import_statistics:
      required: false
      selector:
        boolean:
    config_entry_id:
      required: false
      selector:
        text:
    run_in_background:
      required: false
      selector:
        boolean:
